version: "3"
services:
  aiogram-app:
    build: DealMakerBot/.
    env_file:
      - DealMakerBot/.env
    depends_on:
      - redis
      - database-api
    environment:
      DB_API_URL: https://dealmakerbot.xyz
      DB_API_TOKEN:
      REDIS_PASSWORD:
      REDIS_HOST:
    command: ["python", "main_webhook.py"]
    ports:
      - "8080:8080"
    volumes:
      - ./DealMakerBot/admin_sessions:/app/admin_sessions

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "", "--databases", "10"]
    volumes:
      - redis_data:/data

  postgres-db:
    image: postgres:16.1-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dealbotdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - postgres_dealbot:/var/lib/postgresql/dealbot_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  database-api:
    build: BotMonobankIntegration/.
    env_file:
      - BotMonobankIntegration/.env
    environment:
      POSTGRES_HOST: postgres-db
      POSTGRES_PASSWORD:
    depends_on:
      - postgres-db
    ports:
      - "8088:8088"
    command: >
      sh -c "
        alembic upgrade heads &&
        uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8088
      "

volumes:
  postgres_dealbot:
  redis_data:
