version: "3"
services:
  aiogram-app:
    build: DealMakerBot/.
    env_file:
      - DealMakerBot/.env
    depends_on:
      - redis
      - database-api
    environment:
      DB_API_URL: database-api
      DB_API_TOKEN:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "", "--databases", "10"]
    volumes:
      - redis_data:/data

  postgres-db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dealmakerbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  database-api:
    build: BotMonobankIntegration/.
    env_file:
      - BotMonobankIntegration/.env
    depends_on:
      - postgres-db
      - nginx
    ports:
      - "80:80"
    command: >
      sh -c "
        alembic upgrade heads &&
        uvicorn main:app --proxy-headers --host 0.0.0.0 --port 80
      "

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
  redis_data:
