"""Added supergroup id and chat type

Revision ID: 5ca6d1f9f205
Revises: fee143733aaa
Create Date: 2023-12-04 16:33:52.630271

"""
from alembic import op
import sqlalchemy as sa
from aiogram.enums import ChatType

# revision identifiers, used by Alembic.
revision = '5ca6d1f9f205'
down_revision = 'fee143733aaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE TYPE chattype AS ENUM ('SENDER', 'PRIVATE', 'GROUP', 'SUPERGROUP', 'CHANNEL');")
    op.add_column('chats', sa.Column('supergroup_id', sa.BIGINT(), nullable=True))
    op.add_column('chats', sa.Column('chat_type', sa.Enum('SENDER', 'PRIVATE', 'GROUP', 'SUPERGROUP', 'CHANNEL',
                                                          name='chattype'), nullable=False,
                                     server_default=ChatType.GROUP))
    op.create_unique_constraint("unique_sg_id", 'chats', ['supergroup_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_sg_id", 'chats', ['supergroup_id'])

    op.drop_column('chats', 'chat_type')
    op.drop_column('chats', 'supergroup_id')
    op.execute("DROP TYPE chattype;")
    # ### end Alembic commands ###
