"""empty message

Revision ID: 6c9ab55b9bd2
Revises: 5ca6d1f9f205
Create Date: 2023-12-07 14:36:40.590361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9ab55b9bd2'
down_revision = '5ca6d1f9f205'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_messages', sa.Column('has_files', sa.Boolean(), nullable=False,
                                              server_default=sa.sql.expression.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_messages', 'has_files')
    # ### end Alembic commands ###
