"""Adding field 

Revision ID: 730212372cbf
Revises: adc74d2bab2d
Create Date: 2023-11-28 20:58:50.558172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730212372cbf'
down_revision = 'adc74d2bab2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("constraint_user_balance_id", 'balance', ['user_id'])
    op.add_column('chats', sa.Column('chat_admin', sa.String(), nullable=False))
    op.create_unique_constraint("constaint_exec_id", 'executors', ['executor_id'])
    op.create_unique_constraint("constraint_group_id", 'group_messages', ['group_message_id'])
    op.create_unique_constraint("constrain_task_id", 'tasks', ['task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("constaint_exec_id", 'executors', ['executor_id'])
    op.create_unique_constraint("constraint_group_id", 'group_messages', ['group_message_id'])
    op.create_unique_constraint("constrain_task_id", 'tasks', ['task_id'])
    op.drop_column('chats', 'chat_admin')
    op.create_unique_constraint("constraint_user_balance_id", 'balance', ['user_id'])
    # ### end Alembic commands ###
