"""Add commission field to WithdrawalRequest

Revision ID: bd0bc950c969
Revises: 730212372cbf
Create Date: 2023-11-29 18:20:21.011217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0bc950c969'
down_revision = '730212372cbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal_requests', sa.Column('commission', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawal_requests', 'commission')
    # ### end Alembic commands ###
