"""Create new unique constraint

Revision ID: fee143733aaa
Revises: bd0bc950c969
Create Date: 2023-11-30 14:28:26.111507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee143733aaa'
down_revision = 'bd0bc950c969'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_client_id_key', 'chats', type_='unique')
    op.drop_constraint('chats_executor_id_key', 'chats', type_='unique')
    op.create_unique_constraint('unique_combination_chat', 'chats', ['chat_id', 'task_id', 'executor_id', 'client_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_combination_chat', 'chats', type_='unique')
    op.create_unique_constraint('chats_executor_id_key', 'chats', ['executor_id'])
    op.create_unique_constraint('chats_client_id_key', 'chats', ['client_id'])
    # ### end Alembic commands ###
